### ISSUE TITLE
IndexError: index 5534 is out of bounds for axis 0 with size 5534

### ISSUE THREAD

**Issue by hamsunwoo** [Team1-TU-tech/ml#1]
## 에러메세지
```bash
Traceback (most recent call last):
  File "/Users/seon-u/TU-tech/ml/src/ml/main.py", line 43, in <module>
    similar_performances = get_top_similar_performances(cosine_sim, performances)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon-u/TU-tech/ml/src/ml/utils.py", line 85, in get_top_similar_performances
    performance_similarities = cosine_sim[idx]  # 해당 공연과 다른 공연들의 유사도
                               ~~~~~~~~~~^^^^^
IndexError: index 5534 is out of bounds for axis 0 with size 5534
```

**Comment by hamsunwoo** [comment]
## 해결방법 
### before
```bash
def get_top_similar_performances(cosine_sim, performances, top_n=3):
    similar_performances = []
    
    # 각 공연에 대해 유사한 공연들을 찾기
    for idx, performance in enumerate(performances):
        performance_similarities = cosine_sim[idx]  # 해당 공연과 다른 공연들의 유사도
        performance_start_date = datetime.strptime(performance['start_date'], '%Y.%m.%d')  # 공연 시작 날짜
        
        # 유사도 높은 순으로 정렬하되, 자기 자신은 제외
        similar_performances_idx = np.argsort(performance_similarities)[::-1][1:top_n+1]  # 유사도 높은 순
        
        # 유효한 인덱스만 선택 (범위를 벗어난 인덱스를 제외)
        similar_performances_idx = similar_performances_idx[similar_performances_idx < len(performances)]
        
        # 유효한 공연들의 유사도 정보 저장
        top_similar = []
        
        for i in similar_performances_idx:
            if i >= len(performances):
                continue
```

### after
```bash
# 각 공연에 대해 유사한 공연들을 찾기
    for idx, performance in enumerate(performances):
        if idx >= len(cosine_sim):  # idx가 cosine_sim의 범위를 벗어나지 않도록 체크
            print(f"Index {idx} is out of bounds for cosine_sim with size {len(cosine_sim)}")
            continue
        
        performance_similarities = cosine_sim[idx]  # 해당 공연과 다른 공연들의 유사도
        performance_start_date = datetime.strptime(performance['start_date'], '%Y.%m.%d')  # 공연 시작 날짜
        
        # 유사도 높은 순으로 정렬하되, 자기 자신은 제외
        similar_performances_idx = np.argsort(performance_similarities)[::-1][1:top_n+1]  # 유사도 높은 순

        # 유효한 인덱스만 선택 (범위를 벗어난 인덱스를 제외)
        similar_performances_idx = similar_performances_idx[similar_performances_idx < len(performances)]
        
        # 유효한 공연들의 유사도 정보 저장
        top_similar = []
        
        for i in similar_performances_idx:
            if i >= len(performances):
                continue  # 범위를 벗어난 인덱스는 건너뜀
```
